GET http://localhost:8888/api/register
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ1c2VyMkBnbWFpbC5jb20iLCJzY29wZSI6WyJhbGwiXSwic3Vic2NyaXB0aW9uIjpudWxsLCJleHAiOjE1OTEwMDQ3MTMsInVzZXJJZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IjIzODMzY2I1LTczZTEtNDc4Yy04ZjI5LTkxYzMzMzBkZjdiOSIsImNsaWVudF9pZCI6InRyY2tsc3QifQ.22Fb5H-MFZi4QL8VhlcelKDODuO0tx_nRVcj_FGh0jc

###
POST http://localhost:8888/api/register
Content-Type: application/json

{
  "username": "user2@gmail.com",
  "password": "user"
}

###
POST http://localhost:8888/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic trcklst secret

password=user&username=user2@gmail.com&grant_type=password

###
POST http://localhost:8888/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ1c2VyMkBnbWFpbC5jb20iLCJzY29wZSI6WyJhbGwiXSwic3Vic2NyaXB0aW9uIjpudWxsLCJleHAiOjE1OTEwMDQ3MTMsInVzZXJJZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IjIzODMzY2I1LTczZTEtNDc4Yy04ZjI5LTkxYzMzMzBkZjdiOSIsImNsaWVudF9pZCI6InRyY2tsc3QifQ.22Fb5H-MFZi4QL8VhlcelKDODuO0tx_nRVcj_FGh0jc
Content-Type: application/json